### ISSUE TITLE
WebColl corpus has no download link

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#1]
WebColl is not in Lindat repository for some reason, so the download link goes to corpora list. Find a suitable link and a corpus description.

**Comment by stranak** [comment]
WebColl is problematic in IPR, so it is not in LINDAT repository either, for instance. Maybe we should remove it from Kontext. 

What good alternatives do we have, though? I see the Czech corpus in Martin Majlis' W2C: http://hdl.handle.net/11858/00-097C-0000-0022-6133-9 Is it similar in size? What else? Can we get CzTenTen from Brno?

**Comment by stranak** [comment]
You can have a look at this processed Czech dataset (data from Common Crawl project): http://data.statmt.org/ngrams/deduped/ The URL says ngrams, but is should be full texts, according to the [README file](http://data.statmt.org/ngrams/deduped/Readme).

**Comment by stranak** [comment]
Anyway, WebColl is a small corpus and the same domain as at least two larger coorpora we already have in Kontext: http://lindat.mff.cuni.cz/services/kontext/run.cgi/first_form?corpname=czes_cz_w and http://lindat.mff.cuni.cz/services/kontext/run.cgi/first_form?corpname=cwc_11_cs_w

So when either of them is tagged, WebColl can be removed from Kontext. 

And we will see about adding some bigger corpora mentioned above later.

**Comment by natalink** [comment]
The tagged and parsed corpus is added: https://lindat.mff.cuni.cz/services/kontext/run.cgi/first_form?corpname=parsedcwc_cs_a . It's only 3,8 GB, so 5 times bigger than WebColl. We should also inspect the quality of data in CWC.

**Comment by kosarko** [comment]
@stranak @Ansa211 what's the status of this issue? are we removing webcoll from production or keeping it?

@vidiecan currently there's no download link on the production; just info

**Comment by stranak** [comment]
This corpus cannot be made available for download, but I would keep it available for search. 

--pavel 



21. 8. 2017 v 13:51, Ondřej Košarko <notifications@github.com>:

**Comment by kosarko** [comment]
> This corpus cannot be made available for download, but I would keep it available for search.

@vidiecan can we close this one then?

**Comment by Ansa211** [comment]
I think so!
