### ISSUE TITLE
Other UI non-intuitive issues

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-kontext#11]
- KonText logo should point to the list of corpora, not to the search page of some corpus
- Maybe we can also put some explicit link 'List of corpora', so far it is accessible only via menu Help

**Comment by Kira-D** [comment]
Release-0.9: <logo_href> tag from config.xml is responsible for this behavior.
All we need is to change the link to http://path/to/corpora/corplist

**Comment by vidiecan** [comment]
seems to be fixed

**Comment by kosarko** [comment]
yup, seems ok
