### ISSUE TITLE
Logged Exception CorpInfoNotFound 

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#110]
```Message
CorpInfoNotFound (/opt/DATA/kontext/corpora/registry/ud_eu_a;lemma=;lpos=;align=)
Traceback (most recent call last):
File "/opt/kontext/deploy/source/public/../lib/controller.py", line 794, in run
self._pre_action_validate()
File "/opt/kontext/deploy/source/public/../lib/controller.py", line 507, in _pre_action_validate
raise err
CorpInfoNotFound: CorpInfoNotFound (/opt/DATA/kontext/corpora/registry/ud_eu_a;lemma=;lpos=;align=)```

**Comment by Ansa211** [comment]
Not sure if this is related:
I've been getting 
`corpinfo: CorpInfoNotFound (/corpora/registry/test_la_m)`
during compilation when I tried to run `compilecorp` without the MANATEE_REGISTRY variable set,
or when it is set correctly to
`MANATEE_REGISTRY=/opt/projects/lindat-services-kontext/devel/data/corpora/registry`
but the file `/corpora/registry/test_la_m` does not exist.

**Comment by vidiecan** [comment]
closing this one as it seems it stopped happening in the latest version
