### ISSUE TITLE
No bar chart in frequency distribution

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#114]
https://wiki.korpus.cz/doku.php/kurz:vyhodnoceni_dotazu#frekvencni_distribuce_slovnich_tvaru namely https://wiki.korpus.cz/lib/exe/detail.php/kurz:lemma_slovni_tvary_bezvelkych.png?id=kurz%3Avyhodnoceni_dotazu is the chart a new addition or is there something broken?

**Comment by vidiecan** [comment]
closing, cannot reproduce in the latest version (I see the bars)
