### ISSUE TITLE
Going to View before running a query causes "Error 404"

### ISSUE THREAD

**Issue by Ansa211** [ufal/lindat-kontext#115]
`Query` > `Enter new query` -> select a corpus -> `View` > `Attributes, structures and references` -> "Apply view options" -> Error 404: The requested page `https://lindat.mff.cuni.cz/en/first_form` can't be found

I think it makes sense to be able to adjust the view even before running a query, so I do not suggest to grey out the corpus specific menu `View`>`Attributes, structures and references` before running a query, even though it would almost certainly solve the problem

**Comment by kosarko** [comment]
You definitely shouldn't end up at ttps://lindat.mff.cuni.cz/en/first_form (no services/kontext in the url)
