### ISSUE TITLE
Invalid pid in fcs reply

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#118]
https://lindat.mff.cuni.cz/services/fcs-kontext/?operation=searchRetrieve&version=1.2&query=test&startRecord=1&maximumRecords=10&x-cmd-context=w2c_en_a&recordSchema=http%3A%2F%2Fclarin.eu%2Ffcs%2F1.0

contains 

```
<fcs:Resource pid='ovm_cs_w' ref='ovm_cs_w'>
```

**Comment by kosarko** [comment]
should that be the handle of the ovm corpus in repository or what?

**Comment by vidiecan** [comment]
according to the FCS standard, pid in Resource shoud be PID of the resource, ref is more complicated but at least it should contain the correct corpora name
