### ISSUE TITLE
kontext icon has wrong link on kontext-staging

### ISSUE THREAD

**Issue by Ansa211** [ufal/lindat-kontext#119]
This is a minor issue, but I run into it several times a day, so it would be nice if it could be solved:

on `kontext-staging`, clicking the `kontext` icon in the left top corner attempts to open `https://lindat.mff.cuni.cz/en/kontext` instead of the expected `https://lindat.mff.cuni.cz/services/kontext-staging/ansa/corpora/corplist`

**Comment by Kira-D** [comment]
Done.
This was a config-specific issue: correct value of logo_href parameter in config.xml
