### ISSUE TITLE
Create subcorpora results in exception

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#124]
```'ascii' codec can't decode byte 0xc4 in position 0: ordinal not in range(128)```

**Comment by kosarko** [comment]
can you provide steps to reproduce in old versions? Or where's the issue; in how the corpora is encoded? What encoding are our corpora in?

**Comment by vidiecan** [comment]
we do not have such corpora

**Comment by vidiecan** [comment]
should be fixed but cannot reproduce
