### ISSUE TITLE
Corpora auth UI/UX

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#130]
@stranak you did have some comments regarding the ui/ux; wanting it to be more like pmltq or something...can you be more specific? Is it just about the look and size of the locks? I tried to see what pmltq does when you are logged in and can't access a corpus, but didn't find any that I couldn't access...

**Comment by stranak** [comment]
> On 1 Nov 2017, at 15:28, Ondřej Košarko <notifications@github.com> wrote:
> 
> @stranak <https://github.com/stranak> you did have some comments regarding the ui/ux; wanting it to be more like pmltq or something...can you be more specific? Is it just about the look and size of the locks? I tried to see what pmltq does when you are logged in and can't access a corpus, but didn't find any that I couldn't access...
> 
Yeah, 2 things.
1) I doo like the way locks are placed and look in PML-TQ. Look at https://lindat.mff.cuni.cz/services/pmltq/#!/treebanks when you are not logged in, maybe filter to Penn Treebank.

2) I do also like the way it works: popup to log in directly on that page , if you close the popup you stay there. If you do login, you are only then redirected to the query page for that corpus.

**Comment by Kira-D** [comment]
@stranak the second thing is quite problematic.
As we discussed with @vidiecan, this implementation uses iframe technology, which is often used for phishing and abuse. Some of the identity providers refused to work with iframe. The solution based on iframe would limit our users and poses a potential security issue. Thus we would rather use the current implementation, which redirects a user to a standalone page.

**Comment by vidiecan** [comment]
closing as AUTH/AUTHZ works and locks are in the UI
