### ISSUE TITLE
Apply view options does not work

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#136]
https://lindat.mff.cuni.cz/services/kontext/options/viewattrs?ctxattrs=word&attr_vmode=visible&pagesize=40&refs=&viewmode=kwic&attrs=word&corpname=ud_13_eu_a&structs=p%2Cg%2Cerr%2Ccorr&attr_allpos=kw

change -> Apply

**Comment by kosarko** [comment]
Isn't this #115 ?
