### ISSUE TITLE
wrong highlighting

### ISSUE THREAD

**Issue by Ansa211** [ufal/lindat-kontext#156]
[CQL query `<s/> containing [lemma="pes|kočka"]`, sentence view](https://lindat.mff.cuni.cz/services/kontext-staging/ansa/view?ctxattrs=word&attr_vmode=visible&pagesize=40&refs=%3Ddoc.id&q=~lYup3B7l&viewmode=sen&attrs=word&corpname=vyhlasky_cs_a&attr_allpos=kw&structs=s&fromp=1)

a long sentence is not highlighted in full
also the highlighting in the context box at the bottom of the screen seems wrong

![wrong_highlighting](https://user-images.githubusercontent.com/1833866/33531104-25d3863a-d889-11e7-9b92-0a8ed6a72456.png)

**Comment by Ansa211** [comment]
moved to https://github.com/czcorpus/kontext/issues/2061

**Comment by kosarko** [comment]
the context box seems ok to me in the current version. @Ansa211 please verify and reopen if not working as you expect
