### ISSUE TITLE
migration 0.5->0.8

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-kontext#16]
**What did not work in 0.5 that can be fixed after the update:**
- insert tag
- display whole document
- corpus-desc-link (corpus-detail-box  in 0.8 ) does not work in 0.5

**What do we want to leave from 0.5**
-hierarchical display of corpora (tree-component(0.5) vs. corplist-widget(0.8))

**Comment by natalink** [comment]
Some issues for lindat version 0.8 that need to be done:

- On the list of corpora (button Corpus), the items are displayed as name of registry files, not the corpora names.

- Parallel corpora in Lindat are always bi-parallel, and there are more languages than Czech involved (e.g.. English-Tamil, or English-Russian). In CNC, it is necessary to chose a pair to Czech, in lindat the pair to a language should appear by default, like it was in 0.5. 

- Add language flags and make English a default

- adjust lindat-auth-bar (Tomas promised to help with it, but he does not know Shibboleth). So far we have not used local accounts in KonText, maybe we should add it as an option?

**Comment by kosarko** [comment]
I have created issues for the pending tasks; hopefully haven't missed any.
