### ISSUE TITLE
corplist does not like if there are two corplists in config.xml right after each other

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#19]
it will use only the first corplist title

**Comment by kosarko** [comment]
@vidiecan you do not mention which corparch is causing trouble for you. Current lindat_corparch seems to handle it just fine, though the corplist is in external file.

@Ansa211 what you are saying in #59 is that you are currently unable to order the listing as in the following picture, right? In "your" version the three lists would be merged into one?
![image](https://user-images.githubusercontent.com/1842385/29611039-60b40a78-87fc-11e7-8e58-af28b321185d.png)

**Comment by Ansa211** [comment]
Yes, that was the problem. But it is weird anyway because in the Parallel corpora section, there was no problem with multiple corplists just below each other.

**Comment by kosarko** [comment]
closing this one. seems ok on current dev
