### ISSUE TITLE
CQL editing broken in both modes

### ISSUE THREAD

**Issue by Ansa211** [ufal/lindat-kontext#198]
- [ ] I tried to enter the following CQL query into the query form:

`(meet 1:[] 2:[] -5 5)`

but when I get to the first 5, the "-5" is erased and the cursor jumps to the beginning of the input field.

- [ ] So I went to `View > General view options` and unticked `Use advanced CQL editor (experimental):`; but then the input field became unresponsive until I reloaded the page.

**Comment by tomachalek** [comment]
I've created a copy of this issue in the upstream as it is probably up to me to fix the bug.
