### ISSUE TITLE
Missing localisations in Word list

### ISSUE THREAD

**Issue by TomazErjavec** [ufal/lindat-kontext#26]
In the "Word List" screen the final frame "Output options" is not localised, i.e. its strings are missing from the locale files.

**Comment by vidiecan** [comment]
seems to be fixed in upstream
https://github.com/czcorpus/kontext/blob/a66932a1c225637a20d5cc1c8cfd71b9534dcc79/public/files/js/views/messages.json#L520

**Comment by vidiecan** [comment]
closing but followup in #21
