### ISSUE TITLE
Crash with Word List / AFR @ CLARIN.SI

### ISSUE THREAD

**Issue by TomazErjavec** [ufal/lindat-kontext#28]
On our installation (www.clarin.si/kontext/) when we try to use Query -> Word List with output options "ARF" or "Document counts", it seems to call a function that does not exist in Manatee (we have  installed the newest version, manatee-open-2.137.2, dated 1. 7. 2016 and it didn't exist in manatee-open-2.130.6, dated 12. 11. 2015 or some of the tested earlier versions).

``` 
Traceback (most recent call last):
  File "../lib/corplib.py", line 708, in create_arf_db
    arf = corp.count_ARF(attr.id2poss(i), freq)
  File "/usr/local/lib/python2.7/dist-packages/manatee.py", line 847, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Corpus, name)
  File "/usr/local/lib/python2.7/dist-packages/manatee.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/local/lib/python2.7/dist-packages/manatee.py", line 69, in _swig_getattr_nondynamic
    return object.__getattribute__(self, name)
AttributeError: 'Corpus' object has no attribute 'count_ARF'
```
 
Is there another version of Manatee we should use or what would be the solution, as this obviously works on the Czech installation.

**Comment by kosarko** [comment]
@TomazErjavec: can only provide our version info at the moment. Maybe you could try that version, just to be sure...

We are running `'open-2.83.3'`

```
>>> manatee.version()
'open-2.83.3'
>>> inspect.getsourcelines(manatee.Corpus.count_ARF)
(['    def count_ARF(self, *args): return _manatee.Corpus_count_ARF(self, *args)\n'], 487)
```

**Comment by vidiecan** [comment]
@kosarko provide more details e.g., which `pyd` they should be looking for, in which directory etc.

**Comment by TomazErjavec** [comment]
Yes, it turns out it was a version problem - it works fine with your version. But note that your version is from 2013, maybe time to think of an upgrade...
In any case, thanks for your help!
