### ISSUE TITLE
"Output type" missing in Wordlist

### ISSUE THREAD

**Issue by TomazErjavec** [ufal/lindat-kontext#31]
In (no)SketchEngine as well as in the CNC Kontext there is an option "Output type" under Word List / Output options, which enables you to specify multiple output attributes. 
This is very useful in cases where the output attribute should be different from the one over which the search was performed, e.g. to list all the word-forms of a particular lemma, or all lemmas of a particular PoS tag. 
But this option is missing in the LINDAT Kontext - it would be great if it were added.

**Comment by vidiecan** [comment]
@TomazErjavec it is present in 0.9, please confirm and close

**Comment by TomazErjavec** [comment]
Indeed, the option is now available, thanks.
