### ISSUE TITLE
Debugging howto

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#51]
A howto for debugging issues on staging. Python and JS. Remotely if possible.

**Comment by kosarko** [comment]
If you enable debug in configs; there's a python console available at .../console. You can switch to console also from stack trace

**Comment by vidiecan** [comment]
User friendly usages:
1) pycharm + remote interpreter via SSH + Windows Subsystem for Linux
2) pycharm + remote interpreter via SSH + port forwarding to kontext{-dev}
3) kontext.log and logging messages directly in an instance

For the moment, they should help in most of the cases.
