### ISSUE TITLE
Treex view: re-implement the feature in release 0.9

### ISSUE THREAD

**Issue by Kira-D** [ufal/lindat-kontext#53]
Treex view functionality is needed in release 0.9

Connected issue: https://github.com/ufal/lindat-kontext/issues/9

**Comment by stranak** [comment]
Should we still visualise JSON (which might have additional attributes not present in the vertical format, etc.), or directly the vertical data?

*If* we want the second option, @foxik has clearly done that [here](http://lindat.mff.cuni.cz/services/udpipe/)

**Comment by Ansa211** [comment]
The real difference between the JSON way and generating trees from the vertical comes with data from the PDT-family, where the json file contains a lot more information that we want to have in the vertical data. Also, I am not sure if the vertical-to-tree way allows for generating multiple trees simultaneously (see the image), or visualising coreferrence relations etc.

Compare similar trees in our and UCNK style:

![ufal](https://user-images.githubusercontent.com/1833866/29772185-dd04dc84-8bf7-11e7-949c-bed4b669e569.png)
![ucnk](https://user-images.githubusercontent.com/1833866/29772188-e10436cc-8bf7-11e7-8a6b-073ab4b5003a.png)

**Comment by kosarko** [comment]
@vidiecan are we displaying just the a-trees in the 0.12?

**Comment by vidiecan** [comment]
yes, fixed in the latest version
