### ISSUE TITLE
Corpora versions

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#59]
When there are multiple versions of a corpus (UD 1.2, 1.3, 2.0); we should prominently display the latest one...
Maybe use repo metadata?

@stranak comments?

**Comment by Ansa211** [comment]
Pořadí, v jakém se korpusy zobrazují na úvodní stránce, je dáno pořadím v souboru `kontext-conf/config.xml`; prostě tam dám UD1.3 před UD1.2.

Jiná otázka je, jestli do budoucna to pořadí určovat takto ručně (teď je hodně divné, trochu abecední, ale ne úplně), nebo jestli ho měnit nějakou automatikou.

**Comment by Ansa211** [comment]
Related issue: https://github.com/ufal/lindat-kontext/issues/19 (it is not possible to list UD1.3 and UD1.2 right below each other, because the second grouping is ignored - all corpora from both groups would be listed under the UD 1.3 heading)

**Comment by stranak** [comment]
I think we should actually hide the old versions from the list (and when switching corpora from the query interface) by default. 

Ideally we would use “is replaced by” relation in the repository to do it automatically. 

Compare also SketchEngine.co.uk with their simple link in the list of corpora to also show old versions. 

--Pavel



10. 8. 2017 v 16:04, Anna Vernerová <notifications@github.com>:

**Comment by Ansa211** [comment]
Related, therefore posting here:
based on user's access rights, we distinguish corpora of two kinds, "anonymous" and "authenticated".
We also need a "hidden" variant, i.e. a possibility to hide a corpus from corplist and all the menus but to make it accessible by anyone with a direct link (possibly only after logging in). This would be useful not just for outdated versions, but also for end-of-year reports on projects in progress - we have such a case right now where we only want to share a corpus with the institution giving us money.

**Comment by Ansa211** [comment]
for current corparch, this issue has been replaced by #217, #218, and #230
