### ISSUE TITLE
Corpora requiring authentication

### ISSUE THREAD

**Issue by Ansa211** [ufal/lindat-kontext#60]
The following corpora require authentication:

- [ ] **HamleDT 3.0**, the treebanks from the Patch group (https://lindat.mff.cuni.cz/repository/xmlui/page/licence-hamledt-3.0): `hamledt_30_bn_a, hamledt_30_ca_a, hamledt_30_de_a, hamledt_30_en_a, hamledt_30_es_a, hamledt_30_hi_a, hamledt_30_ru_a` and those that are commented out in `kontext-conf/config.xml`: `hamledt_30_ja_a, hamledt_30_sk_a, hamledt_30_te_a, hamledt_30_tr_a`
- [ ] **PCEDT** `pcedt_20_en_a, pcedt_20_cs_a`
- [ ] maybe also corpora with **academic use** license? `ententen_2011_12_16_en_w`

**Comment by kosarko** [comment]
@Ansa211 can you verify the current production setup? If everything is as it's supposed to, please close this issue.
