### ISSUE TITLE
Flags alignment

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#63]
Let's have the flags, used for switching languages, in the top left corner. The same way repository or the homepage has them.

**Comment by vidiecan** [comment]
@kosarko can we close this one?

**Comment by kosarko** [comment]
@jm are the flags where you wanted them or still bit more to the center?

2017-09-04 10:37 GMT+02:00 Jozef M. <notifications@github.com>:

**Comment by vidiecan** [comment]
it is ok for me - UX designer can comment once we have him ;)
