### ISSUE TITLE
stay on the page upon login

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-kontext#7]
1.  In Lindat-KonText (but not in UCNK-Kontext !!), when you make a query, get a concordance and then decide to log in to use additional functions from the menu, you are redirected back to the search page.

2.  A small enchancement: to menu items in grey make a bubble: "The function will be activated upon login"

**Comment by stranak** [comment]
This is really, REALLY bad issue, that makes us look very amateurish. Give it a priority.

**Comment by natalink** [comment]
Login to KonText should be implemented via shibboleth, and the configuration of apache server should be adjusted ( /etc/apache2/ufal-proxies.conf ). The address of the current url can be passed as a parameter.
