### ISSUE TITLE
login on kontext-dev

### ISSUE THREAD

**Issue by Ansa211** [ufal/lindat-kontext#73]
I need to test features on kontext-dev that are not available without login.

**Comment by vidiecan** [comment]
@Ansa211 can we close this now?

**Comment by Ansa211** [comment]
@vidiecan It seems to me that this stopped working again. At least, my attempts to log in while testing on `kontext-staging/ansa` were not successfull.

**Comment by vidiecan** [comment]
@Ansa211 I hope it is fixed now, can we close it?

**Comment by Ansa211** [comment]
Well it is fixed in the sense that I know I can log in to kontext-dev when I use chrome in anonymous mode or remove cookies. I woudn't call it "fixed", to me it's a workaround, but it's only a minor inconvenience, so we can close the issue or maybe mark it as `wontfix`.

**Comment by kosarko** [comment]
This all is probably just misconfiguration; some of our installations (kontext-staging and production) have the global config `cookie_path_prefix` set to `/`; where in fact it should be set to the same thing as `action_path_prefix`

**Comment by kosarko** [comment]
reconfigured the installation, so closing...(@Ansa211 reopen if it's still broken)
