### ISSUE TITLE
measuring speed

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-kontext#8]
### Testing speed of several services
- [ufal-old](http://lindat.mff.cuni.cz/services/kontext/run.cgi/first?shuffle=1&reload=1&corpname=webcoll_m&queryselector=cqlrow&iquery=&lemma=&lpos=&phrase=&word=&wpos=&char=&cql=[tag%3D%22N.*1.*%22][tag!%3D%22V.*%22]*[tag%3D%22N.*4.*%22][tag!%3D%22V.*%22]*[tag%3D%22V.*%22]+within+%3Cs%2F%3E&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&fc_pos_window_type=both&fc_pos_wsize=5&fc_pos_type=all&sca_doc.id=&sca_doc.wordcount=&sca_s.id=); [ufal-new](http://quest.ms.mff.cuni.cz/kontext-tmp-vm/kontext/run.cgi/first?shuffle=1&reload=1&corpname=webcoll_m&queryselector=cqlrow&iquery=&lemma=&lpos=&phrase=&word=&wpos=&char=&cql=&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&fc_pos_window_type=both&fc_pos_wsize=5&fc_pos_type=all) (test version)
- muni: https://corpora.fi.muni.cz/clarin/run.cgi/list
- ucnk: https://kontext.korpus.cz/
- ucnk: https://kontext.korpus.cz/

I could not compare directly, as there is no mutual corpus present in the services, so I selected corpora of approx. the same size. The corpora have 3 attributes (form,  lemma,  tag).
-   CQL query 
  `[tag="N.*1.*"][tag!="V.*"]*[tag="N.*4.*"][tag!="V.*"]*[tag="V.*"] within <s/>`

| service | Webcoll (130,359,782) | syn 2005 (122,419,382) | Araneum Bohemicum Minus (120M) |
| --- | --- | --- | --- |
| lindat-Kontext | 1m11s | - | - |
| lindat-Kontext - new vm | 38s | - | - |
| ucnk | - | 1m02s | - |
| clarin-muni | - | not evaluated:( | - |
| comenius-NoSke | - | - | 40s – 539,817 hits (4,497.80 per million) |
- CQL query `[tag="N.*1.*" & lemma="s.*"][tag!="V.*"& word="a.*"]*[tag="N.*4.*" & lemma="m.*"][tag!="V.*"]*[tag="V.*" & word=".*o.*"] within <s/>`

| service | Webcoll (130,359,782) | syn 2005 (122,419,382) | Araneum Bohemicum Minus (120M) |
| --- | --- | --- | --- |
| lindat-Kontext | 54s | - | - |
| lindat-Kontext - new vm | 13s | - | - |
| ucnk-Kontext | - | 4s (no results) | - |
| clarin-muni-NoSke | - | not evaluated:( | - |
| comenius-NoSke | - | - | 38s, hits: 114 (0.90 per million) |

So, the complex query is processed for about a minute, a new server should help us a little bit. For some reason, I could not evaluate CQL query within the MUNI service for SYN2005 (am I doing something wrong?).
### performance of Lindat-kontext machines

Old vs.new. Syntactically annotated CWC, 627,518,854 words, 12 attributes:
1. query for syntactic attributes: `[afun="Obj"][afun="Pred"][afun="Sb"] within <s/>`
   old:   1m03s
   new: 32s
2. another query: `[afun="Pred"][afun="Obj"][afun="Sb"] within <s/>`  (a bit changed)
   old: 1m03s
   new: 32s
3. really coplicated query: `[afun="Pred" & lemma="s.*"][afun="Obj" & tag="N.*"][afun="Sb" & tag!="N.*" & p_lemma!="s.*"] within <s/>`
   old: 3m10s
   new: 1m05s

**Comment by vidiecan** [comment]
lindat after upgrade

- webcoll q1 - 1m37s (before 1m11s)
- webcoll q2 - 3m17s (54s)
- cwc q1 - 2m53s (1m03s)
- cwc q2 - 1m49s (1m03s)
- cwc q3 - timeout after cca 4 minutes (3m10s)

**Comment by stranak** [comment]
The key speed improvement from usability perspective might be presenting results as they come, like NoSke. Does anybody know whether it is in plans, or can you estimate how much effort it would take to do it? Feel free to move this question into another issue.

(I also added a similar corpus from another NoSke instance to the benchmarks)

**Comment by vidiecan** [comment]
Summarising - the problematic switch is shuffle. We  have bonito, we should compare it with that local instance

**Comment by vidiecan** [comment]
closing this one, should be reopened when we do another round of perf. testing
