### ISSUE TITLE
No Display options

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#82]
When on the results page (search Zeman in ovm) click Display options - a popup opens but the loading never finishes.
```
common.js?v=9adaba:499 GET http://lindat.mff.cuni.cz/services/kontext-new/options/viewattrs?ctxattrs=word&attr_vmode=visible&pagesize=40&refs=doc&q=~Tlcam56H&viewmode=kwic&attrs=word&corpname=ovm_cs_w&structs=p%2Cg%2Cerr%2Ccorr&attr_allpos=kw&format=json 401 (Unauthorized)
```
is logged

**Comment by kosarko** [comment]
happens only with anonymous users

**Comment by vidiecan** [comment]
seems to be fixed, retest

**Comment by kosarko** [comment]
@vidiecan as mentioned in the comment it works with logged in users, but not with anonymous one. Do you see that?

**Comment by vidiecan** [comment]
confirmed, it is reproducible

**Comment by vidiecan** [comment]
fixed in latest version
