### ISSUE TITLE
UI error message: Failed to process your request. Please try again later or contact system support.

### ISSUE THREAD

**Issue by kosarko** [ufal/lindat-kontext#85]
How to reproduce (not always reproducible):
sk tenten, basic search zeman -> no module named celery AFTER that view->general view click apply

**Comment by vidiecan** [comment]
How to reproduce:
Get results, Concordance->Shuffle, Concordance->Undo

**Comment by vidiecan** [comment]
see https://github.com/czcorpus/kontext/issues/1913
