### ISSUE TITLE
Tags displayed in kwic

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-kontext#89]
https://lindat.mff.cuni.cz/services/kontext-new/view?ctxattrs=word&attr_vmode=mouseover&pagesize=40&refs=%23%2Cdoc%2C%3Ddoc.xdeduplid%2C%3Ddoc.langfilterscore%2C%3Ddoc.contenttype%2C%3Ddoc.ip%2C%3Ddoc.length%2C%3Ddoc.timestamp%2C%3Ddoc.url%2C%3Dp.id%2C%3Dp.wordcount%2C%3Dp.class%2C%3Dp.cfclass%2C%3Dp.heading%2C%3Dp.swratio%2C%3Dp.badreason%2C%3Dp.tokenscount%2C%3Dgap.tokenscount&q=~QNO52BEr&viewmode=kwic&attrs=word%2Clemma%2Ctag%2Clc%2Cpos%2Ck%2Cg%2Cc&corpname=sktenten_2011_12_16&structs=doc%2Cp%2Cg&attr_allpos=kw

```

si ešte viac ako dovtedy vážim život a pravé hodnoty | , | ktorými sa v ňom riadim...</doc><doc xdeduplid=2018595 langfilterscore=0.592655>Arabi prepusti
-- | -- | --



```

**Comment by Ansa211** [comment]
Mně se to zdá v pořádku, v adresním řádku máš (skoro na konci) `structs=doc`, neznamená to, že se ve výstupu budou zobrazovat i `<doc>` a `</doc>`? Akorát snad, že když je zvoleno `attr_vmode=mouseover`, tak by se atributy tagu <doc> měly zobrazovat jen na mouseover (zatímco samotný tag by měl zůstat). I když to z "Display options" dialogu není úplně jasné (tam je volba mezi _mouseover_ a _directly in text_ dost jasně vztažená jen k atributům tokenů, nikoli ke strukturním značkám).

**Comment by vidiecan** [comment]
seems to be fixed in the latest version
